[system]
port = ":3000"
machineId = "1"

[moralis]
xApiKey = "7L9fFRFaUpKOlFoUZi7SN0UBiUWbHgf6tTenyqg19TjPRTGuRS46UMRierHQ3XIs"

[bscscan]
apiKey = "VV6I9K4T1XBXHEZ187XJI51AR2FTHCJ8VV"
urlPrefix = "https://api-testnet.bscscan.com/api"

[contract]
gameNftAddress = "0x9E30e0De5682bced703275fb4dCad78EddCC592D"
governanceTokenAddress = "0xe36A654e5B5CC3678f4824a23e7B24e0A3EC6783"
gameTokenAddress = "0x32661f9851CC487d91A4Edc2ac421D48B4aEE942"
gameVaultAddress = "0xDd77BBAafc52BDfA84Bb98a095dfb715f8280870"
usdcAddress = "0x64544969ed7EBf5f083679233325356EbE738930"

[redis]
address = "192.168.31.244:6380"
password = ""

[chain]
wsNodeAddress = "wss://ws-nd-513-001-835.p2pify.com/16ead84fd5bde769914b64a03ecde444"
rpcNodeAddress = "https://nd-513-001-835.p2pify.com/16ead84fd5bde769914b64a03ecde444"

[mysql]
path = "192.168.0.104"
port = "3309"
dbName = "spike_frame_server"
username = "root"
password = "123456"
maxIdleConns = 0
maxOpenConns = 0

[signService]
taskThreshold = 1000
schedInterval = 1

[[signWorkers]]
walletAddress = "0x550bB66C3050C2e9C5DC2b35aa924485b48B67d0"
serverUrl = "http://chris.dag.fan:3000/tx-api/v1/tx/signature"

[[signWorkers]]
walletAddress = "0xc778891fed356fa0ba0d41908a2ccfe341debe60"
serverUrl = "http://chris.dag.fan:3001/tx-api/v1/tx/signature"

[limit]
nftLimit = 12
txRecordLimit = 12

