[System]
Port = ":3000"
MachineId = "1"

[Moralis]
XApiKey = "xx"

[Bscscan]
ApiKey = "xx"
UrlPrefix = "https://api-testnet.bscscan.com/api"

[Contract]
ERC20Contract=["xx","xx","xx"]
NftContract=["xx"]
GameVaultAddress = "xx"


[Redis]
Address = "xx"
Password = "xx"

[Chain]
WsNodeAddress = "xx"
RpcNodeAddress = "xx"

[Mysql]
Path = "xx"
Port = "3309"
DbName = "spike_web3_server"
Username = "root"
Password = "123456"
MaxIdleConns = 0
MaxOpenConns = 0

[SignService]
TaskThreshold = 1000
SchedInterval = 1

[[SignWorkers]]
WalletAddress = "xx"
ServerUrl = "xx"

[[SignWorkers]]
WalletAddress = "xx"
ServerUrl = "xx"

[Limit]
NftLimit = 12
TxRecordLimit = 12

